# **SHETH L.U.J. & SIR M.V. COLLEGE**

**Shreeraj Desai | T075**
### Practical No. 3A
**Aim**: Feature Scaling and Dummification

*   Apply feature-scaling techniques like standardization and normalization to numerical features.
*   Perform feature dummification to convert categorical variables into numerical representations.



In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
feature = df[['avg_income']].values

minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scaler.fit_transform(feature)
print(scaled_feature)

[[0.64312977]
 [0.61450382]
 [0.73091603]
 [0.66603053]
 [0.73282443]
 [0.79389313]
 [0.56679389]
 [0.59732824]
 [0.90458015]
 [0.54389313]
 [0.51335878]
 [0.52480916]
 [0.54007634]
 [0.41603053]
 [0.67938931]
 [0.57633588]
 [0.46183206]
 [0.42557252]
 [0.33206107]
 [0.32061069]
 [0.4370229 ]
 [0.57633588]
 [0.70038168]
 [0.26145038]
 [0.76526718]
 [0.42175573]
 [0.72900763]
 [0.35687023]
 [0.58778626]
 [0.73664122]
 [0.61641221]
 [0.49427481]
 [0.67175573]
 [0.46755725]
 [0.66793893]
 [0.63740458]
 [0.48282443]
 [0.45992366]
 [0.48091603]
 [0.64885496]
 [0.55916031]
 [0.45801527]
 [0.64885496]
 [0.65458015]
 [0.50381679]
 [0.32824427]
 [0.6870229 ]
 [0.59732824]
 [0.73473282]
 [0.61068702]
 [0.45801527]
 [0.71946565]
 [0.5648855 ]
 [0.38740458]
 [0.59923664]
 [0.66030534]
 [0.41030534]
 [0.47328244]
 [0.34160305]
 [0.67557252]
 [0.47900763]
 [0.25954198]
 [0.19656489]
 [0.4370229 ]
 [0.51335878]
 [0.33969466]
 [0.42175573]
 [0.23282443]
 [0.38740458]
 [0.57633588]
 [0.03053435]
 [0.34

In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
feature = df[['population_density']].values

scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature)
print(standardized)

print("Mean {}".format(round(standardized.mean())))
print("Standard Deviation: {}".format(standardized.std()))

robust_scaler = preprocessing.RobustScaler()
print(robust_scaler.fit_transform(feature))

[[-0.39288239]
 [-0.0281581 ]
 [-0.46441671]
 [-0.25283632]
 [-0.15074039]
 [-0.83988794]
 [-0.91075057]
 [-1.01049561]
 [-0.33814016]
 [-0.14503108]
 [-0.0345391 ]
 [ 0.1186048 ]
 [ 0.29357842]
 [-0.1235372 ]
 [-0.33478174]
 [-0.51815141]
 [ 0.06386257]
 [-0.50438189]
 [ 0.23010431]
 [-1.05180416]
 [-0.79857938]
 [-0.56382591]
 [-0.56718433]
 [-0.41336874]
 [-1.17203556]
 [-0.2125353 ]
 [-0.16887585]
 [ 0.18476565]
 [-0.06375734]
 [-0.74282963]
 [-0.01035848]
 [-0.2807112 ]
 [-0.81671485]
 [-0.17156259]
 [-0.62830755]
 [ 0.5780365 ]
 [ 0.25294155]
 [-0.69178167]
 [-0.08357201]
 [-0.67666878]
 [ 0.23447025]
 [-0.11413363]
 [-0.29078646]
 [-0.55442233]
 [ 0.01315045]
 [-0.25619474]
 [-0.23033492]
 [-0.68204225]
 [-0.06241398]
 [-0.06039892]
 [-0.40765943]
 [-0.5188231 ]
 [-0.94265555]
 [ 0.15185315]
 [-0.06241398]
 [-0.53796608]
 [-0.2101844 ]
 [-0.21052025]
 [ 0.22002905]
 [-0.31631044]
 [-0.12924651]
 [ 3.52034724]
 [ 1.13754908]
 [ 3.19558814]
 [ 1.80621027]
 [ 0.51825664]
 [ 0.10449

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
features = df[['population_density', 'avg_income', 'avg_rent']].values

normalizer = Normalizer(norm="l2")
print(normalizer.transform(features))

features_l1_norm = Normalizer(norm="l1").transform(features)
print("Sum of the first observation's values: {}".format(features_l1_norm[0].sum()))

[[0.56364236 0.7819903  0.26607982]
 [0.70065533 0.67143867 0.24135498]
 [0.49389156 0.83086363 0.25639179]
 [0.6017271  0.74838865 0.27899627]
 [0.60706416 0.75014793 0.26220448]
 [0.28189828 0.90582273 0.31625707]
 [0.32281039 0.90324074 0.28275362]
 [0.23241771 0.89639737 0.37743047]
 [0.46639184 0.82864718 0.30955211]
 [0.70956422 0.67260144 0.21006171]
 [0.75444415 0.62248515 0.20814961]
 [0.77431884 0.58191016 0.24861796]
 [0.80345171 0.55186245 0.22341259]
 [0.78372666 0.58281043 0.21471963]
 [0.57756528 0.79150737 0.19983602]
 [0.53030609 0.77271912 0.34882749]
 [0.80460986 0.56429712 0.18485595]
 [0.64796618 0.71878361 0.25197211]
 [0.88903433 0.42627564 0.16705397]
 [0.32867151 0.87322321 0.3598003 ]
 [0.46353666 0.81939793 0.33722514]
 [0.51988812 0.8030046  0.29137596]
 [0.45059089 0.82887952 0.33155181]
 [0.80502247 0.54874413 0.22543002]
 [0.09269893 0.91476531 0.39320647]
 [0.75574999 0.61381868 0.22818538]
 [0.6043261  0.75496869 0.25458247]
 [0.8769146  0.45845368 0.14

In [5]:
import pandas as pd
from sklearn.cluster import KMeans

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
features = df[['avg_income', 'happiness_score']].values

clusterer = KMeans(n_clusters=2, random_state=0)
clusterer.fit(features)

df['group'] = clusterer.predict(features)
print(df.head())

       city_name country  population_density  avg_income  \
0      Old Vista  Europe                2775        3850   
1      Beachport  Europe                3861        3700   
2  Valleyborough  Europe                2562        4310   
3           City  Europe                3192        3970   
4          Falls  Europe                3496        4320   

   internet_penetration  avg_rent  air_quality_index  public_transport_score  \
0                  86.4      1310                 43                    52.0   
1                  78.1      1330                 42                    62.8   
2                  80.1      1330                 39                    73.2   
3                  81.2      1480                 60                    49.2   
4                 100.0      1510                 64                    93.7   

   happiness_score  green_space_ratio  group  
0              8.5               23.8      0  
1              8.1               33.1      0  
2              8.

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
features = df[['population_density', 'internet_penetration']].values

features[2, 1] = np.nan

print(features[~np.isnan(features).any(axis=1)])

df.loc[2, 'internet_penetration'] = np.nan
print(df.dropna())

[[ 2775.     86.4]
 [ 3861.     78.1]
 [ 3192.     81.2]
 [ 3496.    100. ]
 [ 1444.     78.5]
 [ 1233.     84.2]
 [  936.     72.4]
 [ 2938.    100. ]
 [ 3513.     88.7]
 [ 3842.     70.6]
 [ 4298.     78.9]
 [ 4819.     76.4]
 [ 3577.     70.1]
 [ 2948.     69.8]
 [ 2402.     64.7]
 [ 4135.     74.5]
 [ 2443.     72.6]
 [ 4630.     74.8]
 [  813.     85.1]
 [ 1567.     79. ]
 [ 2266.     88.7]
 [ 2256.    100. ]
 [ 2714.     54.4]
 [  455.    100. ]
 [ 3312.     88.8]
 [ 3442.     87.5]
 [ 4495.     75. ]
 [ 3755.     79.2]
 [ 1733.     99.7]
 [ 3914.     61.6]
 [ 3109.     88.5]
 [ 1513.    100. ]
 [ 3434.     70.3]
 [ 2074.     87.7]
 [ 5666.     94.1]
 [ 4698.     81.8]
 [ 1885.     75.5]
 [ 3696.     66.1]
 [ 1930.    100. ]
 [ 4643.     82.4]
 [ 3605.     90.1]
 [ 3079.    100. ]
 [ 2294.     84.8]
 [ 3984.     86.2]
 [ 3182.     83.6]
 [ 3259.     91.1]
 [ 1914.     65.8]
 [ 3759.     96.5]
 [ 3765.     97. ]
 [ 2731.     75.6]
 [ 2400.     79. ]
 [ 1138.     84. ]
 [ 4397.    

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

df = pd.read_csv('Datasets/city_lifestyle_dataset.csv')
features = df[['public_transport_score', 'happiness_score']].values

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0,0]
standardized_features[0,0] = np.nan

mean_imputer = SimpleImputer(strategy="mean")
feautres_mean_imputed = mean_imputer.fit_transform(standardized_features)

print("True Value: {}".format(true_value))
print("Imputed Value: {}".format(feautres_mean_imputed[0,0]))

True Value: -0.2530862894061969
Imputed Value: 0.0008464424394864209
